
package gestlab.view;

import gestlab.model.Cliente;
import gestlab.model.Equipo;
import gestlab.model.HistorialEquipos;
import gestlab.model.Usuario;
import gestlab.restfulclient.EquipoClientSsl;
import gestlab.restfulclient.HistorialEquiposClientSsl;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;


/**
 * Classe per gestionar la compra d'un producte
 * @author manel bosch
 */
public class BookEquipDialog extends javax.swing.JDialog {
    
    private final Equipo equipo;
    private final Usuario usuario;
    private final Cliente cliente;
    
    private HistorialEquiposClientSsl heClient;
    private EquipoClientSsl eqClient;
    private HistorialEquipos he;
    
    private Date begining; 
    private Date end;
    private final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private final Date date = new Date(Calendar.getInstance().getTimeInMillis());//Data del dia actual
    Date today = java.sql.Date.valueOf(date.toString());//Data del dia actual amb concepte temps a 0

    /**
     * Crea una finestra per comprar un nou producte
     * @author manel bosch
     * @param parent finestra mare
     * @param modal manté el focus fins a tancar la finestra
     * @param usuario Usuari que està connectat al programa
     * @param cliente Client que fa la compra
     * @param equipo Equip que es vol reservar
     */
    public BookEquipDialog(java.awt.Frame parent, boolean modal, Usuario usuario, Cliente cliente, Equipo equipo) {
        super(parent, modal);
        this.usuario = usuario;
        this.cliente = cliente;
        this.equipo = equipo;
        openClients();
        initComponents();
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitol = new javax.swing.JLabel();
        jPanelDadesProducte = new javax.swing.JPanel();
        jLabelEquipName = new javax.swing.JLabel();
        jTextFieldEquip = new javax.swing.JTextField();
        jLabelBeginingDate = new javax.swing.JLabel();
        jTextFieldBeginingDate = new javax.swing.JTextField();
        jLabelEndDate = new javax.swing.JLabel();
        jTextFieldEndDate = new javax.swing.JTextField();
        jLabelDateFormat = new javax.swing.JLabel();
        jPanelBotons = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelTitol.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabelTitol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitol.setText("GestLab: Reserva");

        jLabelEquipName.setText("Equip:");

        jLabelBeginingDate.setText("Data inici:");

        jTextFieldBeginingDate.setName("begin"); // NOI18N

        jLabelEndDate.setText("Data fi:");

        jTextFieldEndDate.setName("end"); // NOI18N

        jLabelDateFormat.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabelDateFormat.setText("(aaaa-mm-dd)");

        javax.swing.GroupLayout jPanelDadesProducteLayout = new javax.swing.GroupLayout(jPanelDadesProducte);
        jPanelDadesProducte.setLayout(jPanelDadesProducteLayout);
        jPanelDadesProducteLayout.setHorizontalGroup(
            jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadesProducteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEquipName)
                    .addComponent(jLabelBeginingDate)
                    .addComponent(jLabelEndDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDateFormat)
                    .addGroup(jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(jTextFieldBeginingDate)
                        .addComponent(jTextFieldEquip)))
                .addContainerGap())
        );
        jPanelDadesProducteLayout.setVerticalGroup(
            jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadesProducteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEquipName))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBeginingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBeginingDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDateFormat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndDate)
                    .addComponent(jTextFieldEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        jButtonSave.setText("Guardar");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel·lar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonsLayout = new javax.swing.GroupLayout(jPanelBotons);
        jPanelBotons.setLayout(jPanelBotonsLayout);
        jPanelBotonsLayout.setHorizontalGroup(
            jPanelBotonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jButtonCancel)
                .addContainerGap())
        );

        jPanelBotonsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancel, jButtonSave});

        jPanelBotonsLayout.setVerticalGroup(
            jPanelBotonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanelBotons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDadesProducte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitol)
                .addGap(18, 18, 18)
                .addComponent(jPanelDadesProducte, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Mètode per guardar els canvis
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        he = new HistorialEquipos();
        he.setIdcliente(cliente);
        he.setIdequipo(equipo);
        if(checkDates()){
            he.setInicioAlquiler(begining);
            he.setFinalAlquiler(end);
            int doneReserva = heClient.create_JSON(he);
            if(doneReserva == 200 || doneReserva == 204){
                equipo.setEstadoAlquiler(he.isBookedNow(begining, end));
                int doneEquipo = eqClient.edit_JSON(equipo, String.valueOf(equipo.getId()));
                if(doneEquipo == 200 || doneEquipo == 204){
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null,"No s'ha pogut modificar l'estat de disponibilitat de l'equip","Alert !!",JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null,"No s'ha pogut fer la reserva","Alert !!",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"No s'ha pogut fer la reserva","Alert !!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * Mètode per cancelar l'entrada de dades i per tant tancar la finestra
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        heClient.close();
        eqClient.close();
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelBeginingDate;
    private javax.swing.JLabel jLabelDateFormat;
    private javax.swing.JLabel jLabelEndDate;
    private javax.swing.JLabel jLabelEquipName;
    private javax.swing.JLabel jLabelTitol;
    private javax.swing.JPanel jPanelBotons;
    private javax.swing.JPanel jPanelDadesProducte;
    private javax.swing.JTextField jTextFieldBeginingDate;
    private javax.swing.JTextField jTextFieldEndDate;
    private javax.swing.JTextField jTextFieldEquip;
    // End of variables declaration//GEN-END:variables

    /**
     * Mètode per inicialitzar els ClientSsl que accediran al servei RESTful
     * @author manel bosch
     */
    private void openClients(){
        heClient = new HistorialEquiposClientSsl(usuario.getToken());
        eqClient = new EquipoClientSsl(usuario.getToken());
    }
    
    /**
     * Mètode per omplir els camps de text
     * Només es mostra el nom; les dates s'han d'entrar
     * @author manel bosch
     */
    private void fillData(){
        jTextFieldEquip.setText(equipo.getNombre());
        jTextFieldBeginingDate.setText("");
        jTextFieldEndDate.setText("");
    }
    
    /**
     * Mètode per comprovar que les dates són possibles
     * @author manel bosch
     * @return true o false
     */
    public boolean checkDates(){
        String sBegining = jTextFieldBeginingDate.getText();
        String sEnd = jTextFieldEndDate.getText();
        begining = isValidDate(sBegining);
        end = isValidDate(sEnd);
        if(begining != null && end != null && begining.compareTo(end) <= 0){
            if(begining.compareTo(today) == 0){
                if(!equipo.getEstadoAlquiler()){
                    return true;
                }else{
                    JOptionPane.showMessageDialog(null,"L'equip ja està reservat avui","Alert !!",JOptionPane.WARNING_MESSAGE);
                    return false;
                }
            }else if(begining.compareTo(today) > 0){
                return true;
            }else{
                JOptionPane.showMessageDialog(null,"La data d'inici no pot ser anterior a la d'avui","Alert !!",JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }else{
            JOptionPane.showMessageDialog(null,"La data de fi no pot ser anterior a la d'inici","Alert !!",JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }
    
    /**
     * Mètode per convertir una cadena de text en una data vàlida
     * @author manel bosch
     * @param dateString cadena de text
     * @return Data entrada com a text
     */
    public Date isValidDate(String dateString){
        try {
            java.util.Date d = (java.util.Date) sdf.parse(dateString);
            Date sqlDate = new Date(d.getTime());
            return sqlDate;
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null,"La data entrada; "+dateString+", no és correcte","Alert !!",JOptionPane.WARNING_MESSAGE);
            return null;
        }
    }
}
