
package gestlab.view;

import gestlab.model.Empresa;
import gestlab.restfulclient.EmpresaClient;
import javax.swing.JOptionPane;

/**
 * Classe que gestiona la finestra d'entrada/modificació de dades d'una empresa
 * @author manel bosch
 */
public class CompanyDialog extends javax.swing.JDialog {
    
    Empresa empresa;
    private EmpresaClient eClient;

    /**
     * Crea un nou formulari per entrar dades d'una nova empresa
     * @author manel bosch
     * @param parent finestra mare
     * @param modal manté el focus fins a tancar la finestra
     */
    public CompanyDialog(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        openClient();
        initComponents();
    }
    
    /**
     * Crea un nou formulari per modificar dades d'empresa passada per paràmetre
     * @author manel bosch
     * @param parent finestra mare
     * @param modal manté el focus fins a tancar la finestra
     * @param e Empresa a modificar
     */
    public CompanyDialog(javax.swing.JDialog parent, boolean modal, Empresa e) {
        super(parent, modal);
        openClient();
        initComponents();
        empresa = e;
        fillCompanyData(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitol = new javax.swing.JLabel();
        jPanelDadesEmpresa = new javax.swing.JPanel();
        jLabelNif = new javax.swing.JLabel();
        jLabelNomEmpresa = new javax.swing.JLabel();
        jLabelAdreca = new javax.swing.JLabel();
        jTextFieldNif = new javax.swing.JTextField();
        jTextFieldNomEmpresa = new javax.swing.JTextField();
        jTextFieldAdreca = new javax.swing.JTextField();
        jPanelBotons = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelTitol.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabelTitol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitol.setText("GestLab: Empresa");

        jLabelNif.setText("NIF:");

        jLabelNomEmpresa.setText("Nom empresa:");

        jLabelAdreca.setText("Adreça:");

        javax.swing.GroupLayout jPanelDadesEmpresaLayout = new javax.swing.GroupLayout(jPanelDadesEmpresa);
        jPanelDadesEmpresa.setLayout(jPanelDadesEmpresaLayout);
        jPanelDadesEmpresaLayout.setHorizontalGroup(
            jPanelDadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadesEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNif)
                    .addComponent(jLabelNomEmpresa)
                    .addComponent(jLabelAdreca))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldAdreca, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(jTextFieldNomEmpresa)
                    .addComponent(jTextFieldNif))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDadesEmpresaLayout.setVerticalGroup(
            jPanelDadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadesEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNif)
                    .addComponent(jTextFieldNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomEmpresa)
                    .addComponent(jTextFieldNomEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdreca)
                    .addComponent(jTextFieldAdreca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSave.setText("Guardar");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonClear.setText("Netejar");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel·lar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonsLayout = new javax.swing.GroupLayout(jPanelBotons);
        jPanelBotons.setLayout(jPanelBotonsLayout);
        jPanelBotonsLayout.setHorizontalGroup(
            jPanelBotonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClear)
                .addGap(61, 61, 61)
                .addComponent(jButtonCancel)
                .addContainerGap())
        );

        jPanelBotonsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancel, jButtonClear, jButtonSave});

        jPanelBotonsLayout.setVerticalGroup(
            jPanelBotonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBotonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonCancel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitol, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelBotons, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDadesEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitol)
                .addGap(18, 18, 18)
                .addComponent(jPanelDadesEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelBotons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Mètode per guardar les noves dades
     * @param evt Event que es produeix en prémer el botó
     */
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if(empresa == null){
            Empresa e = getCompanyData();
            eClient.create_JSON(e);
        }else{
            empresa = getCompanyData();
            String id = empresa.getNif();
            eClient.edit_JSON(empresa, id);
        }
        eClient.close();
        this.dispose(); 
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * Mètode per netejar les dades introduides
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextFieldNif.setText("");
        jTextFieldNomEmpresa.setText("");
        jTextFieldAdreca.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * Mètode per cancelar l'entrada de dades i per tant tancar el programa
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelAdreca;
    private javax.swing.JLabel jLabelNif;
    private javax.swing.JLabel jLabelNomEmpresa;
    private javax.swing.JLabel jLabelTitol;
    private javax.swing.JPanel jPanelBotons;
    private javax.swing.JPanel jPanelDadesEmpresa;
    private javax.swing.JTextField jTextFieldAdreca;
    private javax.swing.JTextField jTextFieldNif;
    private javax.swing.JTextField jTextFieldNomEmpresa;
    // End of variables declaration//GEN-END:variables

    /**
     * Mètode per inicialitzar el EmpresaClient que accedirà al servei RESTful
     * @author manel bosch
     */
    private void openClient(){
        eClient = new EmpresaClient();
    }
    
    /**
     * Mètode per omplir els camps amb les dades de l'empresa passada com a paràmetre
     * @author manel bosch
     */
    private void fillCompanyData(Empresa empresa){
        jTextFieldNif.setText(empresa.getNif());
        jTextFieldNomEmpresa.setText(empresa.getNombreEmpresa());
        jTextFieldAdreca.setText(empresa.getDireccionEmpresa());
    }
    
    /**
     * Mètode per llegir els camps amb les dades entrades per crear l'empresa
     * @author manel bosch
     * @return Empresa amb les dades entrades
     */
    private Empresa getCompanyData(){
        if(checkCompanyFields()){
            Empresa e = new Empresa();
            e.setNif(jTextFieldNif.getText());
            e.setNombreEmpresa(jTextFieldNomEmpresa.getText());
            e.setDireccionEmpresa(jTextFieldAdreca.getText());
            return e;
        }else{
            JOptionPane.showMessageDialog(null,"Omplir tots els camps","Alert !!",JOptionPane.WARNING_MESSAGE);
            return null;
        }
    }
        
    /**
     * Mètode per saber si els camps de l'empresa estan buits
     * @author manel bosch
     * @return true o false
     */
    private boolean checkCompanyFields(){
        return !(jTextFieldNif.getText().equals("")
                ||jTextFieldNomEmpresa.getText().equals("")
                ||jTextFieldAdreca.getText().equals(""));
    }
}
