package gestlab.view;

import gestlab.model.Cliente;
import gestlab.model.Usuario;
import gestlab.restfulclient.ClienteClientSsl;
import gestlab.view.functionality.TablesFunctionality;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.ws.rs.core.GenericType;

/**
 * Classe que gestiona la finestra principal del programa
 * @author manel bosch
 */
public class GestLabFrame extends javax.swing.JFrame {
    
    private final Usuario usuario;
    private String token;
    private Cliente cliente;
    private List<Cliente> clientes;
    
    private ClienteClientSsl cClient;
    
    GenericType<List<Cliente>> gTypeClient = new GenericType<List<Cliente>>(){};
    
    TablesFunctionality tFunc = new TablesFunctionality();

    /**
     * Crea un nou frame GestLabFrame
     * @author manel bosch
     * @param u Usuari que accedeix al programa
     */
    public GestLabFrame(Usuario u) {
        this.usuario = u;
        this.token = u.getToken();

        initComponents();
        
        jButtonCancelModifProfile.setVisible(false);
        //Si l'usuari no és administrador s'amaguen alguns botons i pestanya Usuaris
        if(!usuario.getAdministrador()){
            hideButtons();
        }
        fillProfile();
        jTabbedPaneMain.addChangeListener(changeListener);
    }
    
    /**
     * Mètode per obrir la connexió al servei Cliente
     * @author manel bosch
     */
    private void openClient(){
        cClient = new ClienteClientSsl(token);
    }
    
    /**
     * Mètode per amagar els botons i el panell d'usuaris en cas de no ser un usuari administrador
     * @author manel bosch
     */
    private void hideButtons(){
        jTabbedPaneMain.remove(jPanelUsuaris);
        jButtonNewProduct.setVisible(false);
        jButtonModifProduct.setVisible(false);
        jButtonDelProduct.setVisible(false);
        jButtonNewEquip.setVisible(false);
        jButtonModifEquip.setVisible(false);
        jButtonDelEquip.setVisible(false);
    }
    
    //Listener per controlar els canvis de pestanya de la finestra del programa
    ChangeListener changeListener = (ChangeEvent changeEvent) -> {
        JTabbedPane sourceTabbedPane = (JTabbedPane) changeEvent.getSource();
        int index = sourceTabbedPane.getSelectedIndex();
        if(sourceTabbedPane.getTitleAt(index).equals("Usuaris")){
            cClient.close();
            fillUsersList();
        }else if(sourceTabbedPane.getTitleAt(index).equals("Productes")){
            //TODO
        }else if(sourceTabbedPane.getTitleAt(index).equals("Equipament")){
            //TODO
        }else if(sourceTabbedPane.getTitleAt(index).equals("Perfil")){
            //TODO
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jTabbedPaneMain = new javax.swing.JTabbedPane();
        jPanelPerfil = new javax.swing.JPanel();
        jPanelDadesPersonals = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabelCognom1 = new javax.swing.JLabel();
        jTextFieldCognom1 = new javax.swing.JTextField();
        jLabelCognom2 = new javax.swing.JLabel();
        jTextFieldCognom2 = new javax.swing.JTextField();
        jLabelDni = new javax.swing.JLabel();
        jTextFieldDni = new javax.swing.JTextField();
        jLabelMail = new javax.swing.JLabel();
        jTextFieldMail = new javax.swing.JTextField();
        jLabelTelf = new javax.swing.JLabel();
        jTextFieldTelf = new javax.swing.JTextField();
        jButtonModifProfile = new javax.swing.JButton();
        jButtonChangePasswd = new javax.swing.JButton();
        jButtonCancelModifProfile = new javax.swing.JButton();
        jPanelUsuaris = new javax.swing.JPanel();
        jScrollPaneUsers = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jPanelAdminUser = new javax.swing.JPanel();
        jButtonNewUser = new javax.swing.JButton();
        jButtonModifUser = new javax.swing.JButton();
        jButtonDelUser = new javax.swing.JButton();
        jPanelUserSearch = new javax.swing.JPanel();
        jTextFieldSurname = new javax.swing.JTextField();
        jTextFieldUserId = new javax.swing.JTextField();
        jButtonUserId = new javax.swing.JButton();
        jButtonSearchSurname = new javax.swing.JButton();
        jPanelProductes = new javax.swing.JPanel();
        jPanelAdminProducts = new javax.swing.JPanel();
        jButtonNewProduct = new javax.swing.JButton();
        jButtonModifProduct = new javax.swing.JButton();
        jButtonDelProduct = new javax.swing.JButton();
        jScrollPaneProducts = new javax.swing.JScrollPane();
        jPanelProductSearch = new javax.swing.JPanel();
        jTextFieldProduct = new javax.swing.JTextField();
        jTextFieldProductId = new javax.swing.JTextField();
        jButtonProductId = new javax.swing.JButton();
        jButtonSearchProductName = new javax.swing.JButton();
        jPanelProductGlobal = new javax.swing.JPanel();
        jButtonProductsUsed = new javax.swing.JButton();
        jButtonProductsAvailable = new javax.swing.JButton();
        jButtonBuyProduct = new javax.swing.JButton();
        jPanelEquips = new javax.swing.JPanel();
        jPanelEquipSearch = new javax.swing.JPanel();
        jTextFieldEquip = new javax.swing.JTextField();
        jTextFieldEquipId = new javax.swing.JTextField();
        jButtonEquipId = new javax.swing.JButton();
        jButtonSearchEquipName = new javax.swing.JButton();
        jPanelAdminEquips = new javax.swing.JPanel();
        jButtonNewEquip = new javax.swing.JButton();
        jButtonModifEquip = new javax.swing.JButton();
        jButtonDelEquip = new javax.swing.JButton();
        jScrollPaneEquips = new javax.swing.JScrollPane();
        jPanelProductGlobal2 = new javax.swing.JPanel();
        jButtonEquipsUsed = new javax.swing.JButton();
        jButtonEquipsAvailable = new javax.swing.JButton();
        jButtonBook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("GestLab");

        jTabbedPaneMain.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelName.setText("Nom:");

        jTextFieldNom.setEditable(false);

        jLabelCognom1.setText("Primer cognom:");

        jTextFieldCognom1.setEditable(false);

        jLabelCognom2.setText("Segon cognom:");

        jTextFieldCognom2.setEditable(false);

        jLabelDni.setText("DNI:");

        jTextFieldDni.setEditable(false);

        jLabelMail.setText("email:");

        jTextFieldMail.setEditable(false);

        jLabelTelf.setText("Telèfon:");

        jTextFieldTelf.setEditable(false);

        javax.swing.GroupLayout jPanelDadesPersonalsLayout = new javax.swing.GroupLayout(jPanelDadesPersonals);
        jPanelDadesPersonals.setLayout(jPanelDadesPersonalsLayout);
        jPanelDadesPersonalsLayout.setHorizontalGroup(
            jPanelDadesPersonalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadesPersonalsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadesPersonalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCognom1)
                    .addComponent(jLabelName)
                    .addComponent(jLabelCognom2)
                    .addComponent(jLabelDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadesPersonalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCognom2)
                    .addComponent(jTextFieldCognom1)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(jPanelDadesPersonalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMail)
                    .addComponent(jLabelTelf))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadesPersonalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTelf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanelDadesPersonalsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldMail, jTextFieldTelf});

        jPanelDadesPersonalsLayout.setVerticalGroup(
            jPanelDadesPersonalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadesPersonalsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadesPersonalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadesPersonalsLayout.createSequentialGroup()
                        .addGroup(jPanelDadesPersonalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDni)
                            .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMail))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadesPersonalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelName)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelf)))
                    .addGroup(jPanelDadesPersonalsLayout.createSequentialGroup()
                        .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadesPersonalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCognom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCognom1))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadesPersonalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCognom2)
                    .addComponent(jTextFieldCognom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonModifProfile.setText("Modificar dades");
        jButtonModifProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifProfileActionPerformed(evt);
            }
        });

        jButtonChangePasswd.setText("Canviar Contrassenya");
        jButtonChangePasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangePasswdActionPerformed(evt);
            }
        });

        jButtonCancelModifProfile.setText("Cancelar");
        jButtonCancelModifProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelModifProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPerfilLayout = new javax.swing.GroupLayout(jPanelPerfil);
        jPanelPerfil.setLayout(jPanelPerfilLayout);
        jPanelPerfilLayout.setHorizontalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPerfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelDadesPersonals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPerfilLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonChangePasswd)
                            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                                .addComponent(jButtonModifProfile)
                                .addGap(141, 141, 141)
                                .addComponent(jButtonCancelModifProfile)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPerfilLayout.setVerticalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanelDadesPersonals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifProfile)
                    .addComponent(jButtonCancelModifProfile))
                .addGap(18, 18, 18)
                .addComponent(jButtonChangePasswd)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("Perfil", jPanelPerfil);

        jScrollPaneUsers.setBorder(javax.swing.BorderFactory.createTitledBorder("Llista Usuaris"));

        jTableUsers.setModel(tFunc.createTableModel(Cliente.class, clientes));
        jScrollPaneUsers.setViewportView(jTableUsers);

        jButtonNewUser.setText("Nou Usuari");
        jButtonNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewUserActionPerformed(evt);
            }
        });

        jButtonModifUser.setText("Modificar Usuari");
        jButtonModifUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifUserActionPerformed(evt);
            }
        });

        jButtonDelUser.setText("Eliminar Usuari");
        jButtonDelUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdminUserLayout = new javax.swing.GroupLayout(jPanelAdminUser);
        jPanelAdminUser.setLayout(jPanelAdminUserLayout);
        jPanelAdminUserLayout.setHorizontalGroup(
            jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNewUser, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonModifUser, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDelUser, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanelAdminUserLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonDelUser, jButtonModifUser, jButtonNewUser});

        jPanelAdminUserLayout.setVerticalGroup(
            jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNewUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModifUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDelUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextFieldSurname.setText("Cognom");
        jTextFieldSurname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSurnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSurnameFocusLost(evt);
            }
        });

        jTextFieldUserId.setText("Id");
        jTextFieldUserId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUserIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUserIdFocusLost(evt);
            }
        });

        jButtonUserId.setText("Buscar");
        jButtonUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserIdActionPerformed(evt);
            }
        });

        jButtonSearchSurname.setText("Buscar");
        jButtonSearchSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchSurnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUserSearchLayout = new javax.swing.GroupLayout(jPanelUserSearch);
        jPanelUserSearch.setLayout(jPanelUserSearchLayout);
        jPanelUserSearchLayout.setHorizontalGroup(
            jPanelUserSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUserSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jTextFieldUserId))
                .addGap(18, 18, 18)
                .addGroup(jPanelUserSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSearchSurname)
                    .addComponent(jButtonUserId))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUserSearchLayout.setVerticalGroup(
            jPanelUserSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUserSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchSurname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanelUserSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUserId))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelUsuarisLayout = new javax.swing.GroupLayout(jPanelUsuaris);
        jPanelUsuaris.setLayout(jPanelUsuarisLayout);
        jPanelUsuarisLayout.setHorizontalGroup(
            jPanelUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                    .addGroup(jPanelUsuarisLayout.createSequentialGroup()
                        .addComponent(jPanelUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelAdminUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelUsuarisLayout.setVerticalGroup(
            jPanelUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarisLayout.createSequentialGroup()
                .addGroup(jPanelUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAdminUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelUserSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneMain.addTab("Usuaris", jPanelUsuaris);

        jButtonNewProduct.setText("Nou Producte");

        jButtonModifProduct.setText("Modificar Producte");

        jButtonDelProduct.setText("Eliminar Producte");

        javax.swing.GroupLayout jPanelAdminProductsLayout = new javax.swing.GroupLayout(jPanelAdminProducts);
        jPanelAdminProducts.setLayout(jPanelAdminProductsLayout);
        jPanelAdminProductsLayout.setHorizontalGroup(
            jPanelAdminProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminProductsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAdminProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNewProduct, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonModifProduct, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDelProduct, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanelAdminProductsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonDelProduct, jButtonModifProduct, jButtonNewProduct});

        jPanelAdminProductsLayout.setVerticalGroup(
            jPanelAdminProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNewProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModifProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDelProduct)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPaneProducts.setBorder(javax.swing.BorderFactory.createTitledBorder("Llista Productes"));

        jTextFieldProduct.setText("Nom Producte");
        jTextFieldProduct.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldProductFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldProductFocusLost(evt);
            }
        });

        jTextFieldProductId.setText("Id");
        jTextFieldProductId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldProductIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldProductIdFocusLost(evt);
            }
        });

        jButtonProductId.setText("Buscar");

        jButtonSearchProductName.setText("Buscar");

        javax.swing.GroupLayout jPanelProductSearchLayout = new javax.swing.GroupLayout(jPanelProductSearch);
        jPanelProductSearch.setLayout(jPanelProductSearchLayout);
        jPanelProductSearchLayout.setHorizontalGroup(
            jPanelProductSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jTextFieldProductId))
                .addGap(18, 18, 18)
                .addGroup(jPanelProductSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonProductId)
                    .addComponent(jButtonSearchProductName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelProductSearchLayout.setVerticalGroup(
            jPanelProductSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchProductName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanelProductSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProductId))
                .addContainerGap())
        );

        jButtonProductsUsed.setText("Productes consumits");

        jButtonProductsAvailable.setText("Productes disponibles");

        jButtonBuyProduct.setText("Comprar Producte");

        javax.swing.GroupLayout jPanelProductGlobalLayout = new javax.swing.GroupLayout(jPanelProductGlobal);
        jPanelProductGlobal.setLayout(jPanelProductGlobalLayout);
        jPanelProductGlobalLayout.setHorizontalGroup(
            jPanelProductGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductGlobalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonProductsUsed)
                    .addComponent(jButtonProductsAvailable)
                    .addComponent(jButtonBuyProduct))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelProductGlobalLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonBuyProduct, jButtonProductsAvailable, jButtonProductsUsed});

        jPanelProductGlobalLayout.setVerticalGroup(
            jPanelProductGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductGlobalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonProductsUsed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProductsAvailable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButtonBuyProduct))
        );

        javax.swing.GroupLayout jPanelProductesLayout = new javax.swing.GroupLayout(jPanelProductes);
        jPanelProductes.setLayout(jPanelProductesLayout);
        jPanelProductesLayout.setHorizontalGroup(
            jPanelProductesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductesLayout.createSequentialGroup()
                        .addComponent(jPanelProductSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jPanelProductGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jPanelAdminProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneProducts))
                .addContainerGap())
        );
        jPanelProductesLayout.setVerticalGroup(
            jPanelProductesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductesLayout.createSequentialGroup()
                .addGroup(jPanelProductesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelAdminProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelProductSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelProductGlobal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneMain.addTab("Productes", jPanelProductes);

        jTextFieldEquip.setText("Nom Equip");
        jTextFieldEquip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEquipFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEquipFocusLost(evt);
            }
        });

        jTextFieldEquipId.setText("Id");
        jTextFieldEquipId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEquipIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEquipIdFocusLost(evt);
            }
        });

        jButtonEquipId.setText("Buscar");

        jButtonSearchEquipName.setText("Buscar");

        javax.swing.GroupLayout jPanelEquipSearchLayout = new javax.swing.GroupLayout(jPanelEquipSearch);
        jPanelEquipSearch.setLayout(jPanelEquipSearchLayout);
        jPanelEquipSearchLayout.setHorizontalGroup(
            jPanelEquipSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEquipSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEquipSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldEquip, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jTextFieldEquipId))
                .addGap(18, 18, 18)
                .addGroup(jPanelEquipSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEquipId)
                    .addComponent(jButtonSearchEquipName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEquipSearchLayout.setVerticalGroup(
            jPanelEquipSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEquipSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEquipSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchEquipName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanelEquipSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEquipId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEquipId))
                .addContainerGap())
        );

        jButtonNewEquip.setText("Nou Equip");

        jButtonModifEquip.setText("Modificar Equip");

        jButtonDelEquip.setText("Eliminar Equip");

        javax.swing.GroupLayout jPanelAdminEquipsLayout = new javax.swing.GroupLayout(jPanelAdminEquips);
        jPanelAdminEquips.setLayout(jPanelAdminEquipsLayout);
        jPanelAdminEquipsLayout.setHorizontalGroup(
            jPanelAdminEquipsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminEquipsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAdminEquipsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNewEquip, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonModifEquip, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDelEquip, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanelAdminEquipsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonDelEquip, jButtonModifEquip, jButtonNewEquip});

        jPanelAdminEquipsLayout.setVerticalGroup(
            jPanelAdminEquipsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminEquipsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNewEquip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModifEquip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDelEquip)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPaneEquips.setBorder(javax.swing.BorderFactory.createTitledBorder("Llista Equips"));

        jButtonEquipsUsed.setText("Equips utilitzats");

        jButtonEquipsAvailable.setText("Equips disponibles");

        jButtonBook.setText("Reservar equip");

        javax.swing.GroupLayout jPanelProductGlobal2Layout = new javax.swing.GroupLayout(jPanelProductGlobal2);
        jPanelProductGlobal2.setLayout(jPanelProductGlobal2Layout);
        jPanelProductGlobal2Layout.setHorizontalGroup(
            jPanelProductGlobal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductGlobal2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductGlobal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEquipsUsed)
                    .addComponent(jButtonEquipsAvailable)
                    .addComponent(jButtonBook))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelProductGlobal2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonBook, jButtonEquipsAvailable, jButtonEquipsUsed});

        jPanelProductGlobal2Layout.setVerticalGroup(
            jPanelProductGlobal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductGlobal2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonEquipsUsed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEquipsAvailable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButtonBook))
        );

        javax.swing.GroupLayout jPanelEquipsLayout = new javax.swing.GroupLayout(jPanelEquips);
        jPanelEquips.setLayout(jPanelEquipsLayout);
        jPanelEquipsLayout.setHorizontalGroup(
            jPanelEquipsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEquipsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEquipsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEquipsLayout.createSequentialGroup()
                        .addComponent(jPanelEquipSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jPanelProductGlobal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(jPanelAdminEquips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneEquips))
                .addContainerGap())
        );
        jPanelEquipsLayout.setVerticalGroup(
            jPanelEquipsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEquipsLayout.createSequentialGroup()
                .addGroup(jPanelEquipsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelAdminEquips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelEquipSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelProductGlobal2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneEquips, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneMain.addTab("Equipament", jPanelEquips);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneMain)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Mètode per controlar desaparició del text per defecte
     * @author manel bosch
     * @param evt Event que es produeix en guanyar el focus
     */
    private void jTextFieldSurnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSurnameFocusGained
        if(jTextFieldSurname.getText().trim().equals("Cognom"))
           jTextFieldSurname.setText("");
    }//GEN-LAST:event_jTextFieldSurnameFocusGained

    /**
     * Mètode per controlar l'aparició del text per defecte
     * @author manel bosch
     * @param evt Event que es produeix en perdre el focus
     */
    private void jTextFieldSurnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSurnameFocusLost
        if(jTextFieldSurname.getText().trim().equals("")){
           jTextFieldSurname.setText("Cognom");
        }
    }//GEN-LAST:event_jTextFieldSurnameFocusLost

    /**
     * Mètode per controlar desaparició del text per defecte
     * @author manel bosch
     * @param evt Event que es produeix en guanyar el focus
     */
    private void jTextFieldUserIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUserIdFocusGained
        if(jTextFieldUserId.getText().trim().equals("Id"))
           jTextFieldUserId.setText("");
    }//GEN-LAST:event_jTextFieldUserIdFocusGained

    /**
     * Mètode per controlar l'aparició del text per defecte
     * @author manel bosch
     * @param evt Event que es produeix en perdre el focus
     */
    private void jTextFieldUserIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUserIdFocusLost
        if(jTextFieldUserId.getText().trim().equals("")){
           jTextFieldUserId.setText("Id");
        }
    }//GEN-LAST:event_jTextFieldUserIdFocusLost

    /**
     * Mètode per controlar desaparició del text per defecte
     * @author manel bosch
     * @param evt Event que es produeix en guanyar el focus
     */
    private void jTextFieldProductFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductFocusGained
        if(jTextFieldProduct.getText().trim().equals("Nom Producte"))
           jTextFieldProduct.setText("");
    }//GEN-LAST:event_jTextFieldProductFocusGained

    /**
     * Mètode per controlar l'aparició del text per defecte
     * @author manel bosch
     * @param evt Event que es produeix en perdre el focus
     */
    private void jTextFieldProductIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductIdFocusLost
        if(jTextFieldProductId.getText().trim().equals("")){
           jTextFieldProductId.setText("Id");
        }
    }//GEN-LAST:event_jTextFieldProductIdFocusLost

    /**
     * Mètode per controlar desaparició del text per defecte
     * @author manel bosch
     * @param evt Event que es produeix en guanyar el focus
     */
    private void jTextFieldEquipFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEquipFocusGained
        if(jTextFieldEquip.getText().trim().equals("Nom Equip"))
           jTextFieldEquip.setText("");
    }//GEN-LAST:event_jTextFieldEquipFocusGained

    /**
     * Mètode per controlar l'aparició del text per defecte
     * @author manel bosch
     * @param evt Event que es produeix en perdre el focus
     */
    private void jTextFieldEquipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEquipFocusLost
        if(jTextFieldEquip.getText().trim().equals("")){
           jTextFieldEquip.setText("Nom Equip");
        }
    }//GEN-LAST:event_jTextFieldEquipFocusLost

    /**
     * Mètode per controlar l'aparició del text per defecte
     * @author manel bosch
     * @param evt Event que es produeix en perdre el focus
     */
    private void jTextFieldProductFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductFocusLost
       if(jTextFieldProduct.getText().trim().equals("")){
           jTextFieldProduct.setText("Nom Producte");
        }
    }//GEN-LAST:event_jTextFieldProductFocusLost

    /**
     * Mètode per controlar desaparició del text per defecte
     * @author manel bosch
     * @param evt Event que es produeix en guanyar el focus
     */
    private void jTextFieldProductIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductIdFocusGained
        if(jTextFieldProductId.getText().trim().equals("Id")){
           jTextFieldProductId.setText("");
        }
    }//GEN-LAST:event_jTextFieldProductIdFocusGained

    /**
     * Mètode per controlar desaparició del text per defecte
     * @author manel bosch
     * @param evt Event que es produeix en guanyar el focus
     */
    private void jTextFieldEquipIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEquipIdFocusGained
        if(jTextFieldEquipId.getText().trim().equals("Id")){
           jTextFieldEquipId.setText("");
        }
    }//GEN-LAST:event_jTextFieldEquipIdFocusGained

    /**
     * Mètode per controlar l'aparició del text per defecte
     * @author manel bosch
     * @param evt Event que es produeix en perdre el focus
     */
    private void jTextFieldEquipIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEquipIdFocusLost
        if(jTextFieldEquipId.getText().trim().equals("")){
           jTextFieldEquipId.setText("Id");
        }
    }//GEN-LAST:event_jTextFieldEquipIdFocusLost

    /**
     * Mètode per modificar les dades del perfil
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonModifProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifProfileActionPerformed
        jButtonCancelModifProfile.setVisible(true);
        if(jButtonModifProfile.getText().equals("Modificar dades")){
            enableTextFields(true);
            jButtonModifProfile.setText("Guardar canvis");
        }else if (jButtonModifProfile.getText().equals("Guardar canvis")){
            changeProfile(cliente);
            jButtonModifProfile.setText("Modificar dades");
            jButtonCancelModifProfile.setVisible(false);
            enableTextFields(false);
        }
    }//GEN-LAST:event_jButtonModifProfileActionPerformed

    /**
     * Mètode per buscar un usuari a la base de dades pel seu cognom
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonSearchSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSearchSurnameActionPerformed

    /**
     * Mètode per buscar un usuari a la base de dades pel seu identificador
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUserIdActionPerformed

    /**
     * Mètode per introduir un usuari nou a la base de dades
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewUserActionPerformed
        UserDialog dialog = new UserDialog(this, true, usuario);
        dialog.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosed(WindowEvent e){
                fillUsersList();
            }
        });
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonNewUserActionPerformed

    /**
     * Mètode per modificar un usuari seleccionat 
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonModifUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifUserActionPerformed
        if(jTableUsers.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(null,"Selecciona un client a modificar","Alert !!",JOptionPane.WARNING_MESSAGE);
        }else{
            int row = jTableUsers.getSelectedRow();
            String idClient = (String) jTableUsers.getModel().getValueAt(row,0);
            openClient();
            Cliente c = cClient.find_JSON(Cliente.class, idClient);
            UserDialog dialog = new UserDialog(this, true, usuario, c);
                dialog.addWindowListener(new WindowAdapter(){
                    @Override
                    public void windowClosed(WindowEvent e){
                        fillUsersList();
                    }
                });
            cClient.close();
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_jButtonModifUserActionPerformed

    /**
     * Mètode per eliminar usuari 
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonDelUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelUserActionPerformed
        if(jTableUsers.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(null,"Selecciona un client a eliminar","Alert !!",JOptionPane.WARNING_MESSAGE);
        }else{
            int row = jTableUsers.getSelectedRow();
            String id = (String) jTableUsers.getModel().getValueAt(row,0);
            openClient();
            cClient.remove(id);
            cClient.close();
        }
    }//GEN-LAST:event_jButtonDelUserActionPerformed

    /**
     * Mètode per cridar la finestra per canviar el password
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonChangePasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangePasswdActionPerformed
        PasswordDialog dialog = new PasswordDialog(this, true, usuario);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonChangePasswdActionPerformed

    /**
     * Mètode per cancelar la modificació de dades del perfil
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonCancelModifProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelModifProfileActionPerformed
        jButtonModifProfile.setText("Modificar dades");
        jButtonCancelModifProfile.setVisible(false);
        fillProfile();
        enableTextFields(false);
    }//GEN-LAST:event_jButtonCancelModifProfileActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBook;
    private javax.swing.JButton jButtonBuyProduct;
    private javax.swing.JButton jButtonCancelModifProfile;
    private javax.swing.JButton jButtonChangePasswd;
    private javax.swing.JButton jButtonDelEquip;
    private javax.swing.JButton jButtonDelProduct;
    private javax.swing.JButton jButtonDelUser;
    private javax.swing.JButton jButtonEquipId;
    private javax.swing.JButton jButtonEquipsAvailable;
    private javax.swing.JButton jButtonEquipsUsed;
    private javax.swing.JButton jButtonModifEquip;
    private javax.swing.JButton jButtonModifProduct;
    private javax.swing.JButton jButtonModifProfile;
    private javax.swing.JButton jButtonModifUser;
    private javax.swing.JButton jButtonNewEquip;
    private javax.swing.JButton jButtonNewProduct;
    private javax.swing.JButton jButtonNewUser;
    private javax.swing.JButton jButtonProductId;
    private javax.swing.JButton jButtonProductsAvailable;
    private javax.swing.JButton jButtonProductsUsed;
    private javax.swing.JButton jButtonSearchEquipName;
    private javax.swing.JButton jButtonSearchProductName;
    private javax.swing.JButton jButtonSearchSurname;
    private javax.swing.JButton jButtonUserId;
    private javax.swing.JLabel jLabelCognom1;
    private javax.swing.JLabel jLabelCognom2;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelTelf;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelAdminEquips;
    private javax.swing.JPanel jPanelAdminProducts;
    private javax.swing.JPanel jPanelAdminUser;
    private javax.swing.JPanel jPanelDadesPersonals;
    private javax.swing.JPanel jPanelEquipSearch;
    private javax.swing.JPanel jPanelEquips;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelPerfil;
    private javax.swing.JPanel jPanelProductGlobal;
    private javax.swing.JPanel jPanelProductGlobal2;
    private javax.swing.JPanel jPanelProductSearch;
    private javax.swing.JPanel jPanelProductes;
    private javax.swing.JPanel jPanelUserSearch;
    private javax.swing.JPanel jPanelUsuaris;
    private javax.swing.JScrollPane jScrollPaneEquips;
    private javax.swing.JScrollPane jScrollPaneProducts;
    private javax.swing.JScrollPane jScrollPaneUsers;
    private javax.swing.JTabbedPane jTabbedPaneMain;
    private javax.swing.JTable jTableUsers;
    private javax.swing.JTextField jTextFieldCognom1;
    private javax.swing.JTextField jTextFieldCognom2;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldEquip;
    private javax.swing.JTextField jTextFieldEquipId;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldProduct;
    private javax.swing.JTextField jTextFieldProductId;
    private javax.swing.JTextField jTextFieldSurname;
    private javax.swing.JTextField jTextFieldTelf;
    private javax.swing.JTextField jTextFieldUserId;
    // End of variables declaration//GEN-END:variables

    /*
    Gestió del perfil
    */
    
    /**
     * Mètode per omplir els camps de la pestanya perfil
     * @author manel bosch
     */
    private void fillProfile(){
        openClient();
        cliente = cClient.find_JSON(Cliente.class, usuario.getId());
        jTextFieldNom.setText(cliente.getNombre());
        jTextFieldDni.setText(cliente.getDni());
        jTextFieldCognom1.setText(cliente.getPrimerApellido());
        jTextFieldCognom2.setText(cliente.getSegundoApellido());
        jTextFieldMail.setText(cliente.getEMail());
        jTextFieldTelf.setText(cliente.getTelefono());
        cClient.close();
    }
    
    /**
     * Mètode per habilitar l'entrada de dades als camps de text
     * @author manel bosch
     * @param b Boolean
     */
    public void enableTextFields(Boolean b){
        jTextFieldNom.setEnabled(b);
        jTextFieldCognom1.setEnabled(b);
        jTextFieldCognom2.setEnabled(b);
        jTextFieldMail.setEnabled(b);
        jTextFieldTelf.setEnabled(b);
        jTextFieldNom.setEditable(b);
        jTextFieldCognom1.setEditable(b);
        jTextFieldCognom2.setEditable(b);
        jTextFieldMail.setEditable(b);
        jTextFieldTelf.setEditable(b);
    }
    
     /**
     * Mètode per canviar els camps del client
     * @author manel bosch
     * @param c Client
     */
    public void changeProfile(Cliente c){
        openClient();
        c.setNombre(jTextFieldNom.getText());
        c.setPrimerApellido(jTextFieldCognom1.getText());
        c.setSegundoApellido(jTextFieldCognom2.getText());
        c.setEMail(jTextFieldMail.getText());
        c.setTelefono(jTextFieldTelf.getText());
        cClient.edit_JSON(c, c.getDni());
        cClient.close();
    }
    
    
    /*
    Gestió d'usuaris
    */
    
    /**
     * Mètode per omplir la taula d'usuaris
     * @author manel bosch
     */
    public void fillUsersList(){
        openClient();
        clientes = cClient.findAll_JSON(gTypeClient);
        jTableUsers.setModel(tFunc.createTableModel(Cliente.class, clientes));
        cClient.close();
    }
    
   
}
