package gestlab.view;

import gestlab.model.Usuario;
import gestlab.restfulclient.UsuarioClientSsl;
import gestlab.utils.GestlabConstants;
import org.apache.commons.codec.binary.Base64;


/**
 * Classe que representa l'interfície d'entrada al programa
 * @author manel bosch
 */
public class Login extends javax.swing.JFrame {
    
    private String login;
    private char[] passwd;

    private Usuario usuario;
    private UsuarioClientSsl uClient;
    
    private GestLabFrame gestlabFrame;
    

    /**
     * Crea la interfície de login
     * @author manel bosch
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jPanelEnter = new javax.swing.JPanel();
        jButtonEnter = new javax.swing.JButton();
        jButtonClean = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLogin.setText("Usuari:");

        jLabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPassword.setText("Password:");

        jButtonEnter.setText("Entrar");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jButtonClean.setText("Netejar");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel·lar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEnterLayout = new javax.swing.GroupLayout(jPanelEnter);
        jPanelEnter.setLayout(jPanelEnterLayout);
        jPanelEnterLayout.setHorizontalGroup(
            jPanelEnterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonEnter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClean)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEnterLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancel, jButtonClean, jButtonEnter});

        jPanelEnterLayout.setVerticalGroup(
            jPanelEnterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnter)
                    .addComponent(jButtonClean)
                    .addComponent(jButtonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GestLab");

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLoginLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jPanelEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLoginLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                                        .addComponent(jLabelLogin)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                                        .addComponent(jLabelPassword)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabelMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLoginLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelLogin, jLabelPassword});

        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogin)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jPanelEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMessage)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Mètode per enviar les dades al servidor i si són correctes tancar aquesta finestra i obrir la principal
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        jLabelMessage.setText("");
        getData();
        if(checkPassword(passwd)){
            String pass = encodePasswd(passwd);
            if(checkData(login, pass)){ 
                //Crear el token i afegir-lo a l'usuari ho hauria de fer el servidor
                //L'app només hauria d'obtenir l'usuari amb totes les dades per passar-lo a la finestra principal
                String token = uClient.getToken();
                usuario.setToken(token);
                uClient.edit_JSON(usuario, login);

                uClient.close();
                this.dispose();
                gestlabFrame = new GestLabFrame(usuario);
                gestlabFrame.setVisible(true);
            }else{
                jLabelMessage.setText("Usuari y password incorrectes");
                cleanFields();
            }
        }else{
            jLabelMessage.setText("Password ha de ser de "+ GestlabConstants.PASSWD_MIN_SIZE +" caràcters mínim");
            cleanFields();
        }
        
    }//GEN-LAST:event_jButtonEnterActionPerformed

    /**
     * Mètode per netejar les dades introduides
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
        cleanFields();
    }//GEN-LAST:event_jButtonCleanActionPerformed

    /**
     * Mètode per cancelar l'accés i per tant tancar el programa
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        if (uClient != null){
            uClient.close();
        }
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JPanel jPanelEnter;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables

     /**
     * Mètode per obtenir les dades entrades per pantalla
     * @author manel bosch
     */
    public void getData(){
        login = jTextFieldLogin.getText();
        passwd = jPasswordField.getPassword();
    }
    
    /**
     * Mètode per comprovar les dades entrades per pantalla
     * @author manel bosch
     * @param log login de l'usuari
     * @param pass password de l'usuari codificat amb base64
     * @return true o false
     */
    // En teoria la comprovació es farà al servidor 
    public boolean checkData(String log, String pass){
        boolean acces = false;
        uClient = new UsuarioClientSsl(log, pass);
        usuario = uClient.find_JSON(Usuario.class, log);
        if(usuario != null && usuario.getContrasena().equals(pass)){
            acces = true;
        }
        return acces;
    }
    
    /**
     * Mètode per comprovar si el password entrat té més de 8 caràcters
     * @param pass Password entrat
     * @return true o false
     */
    public Boolean checkPassword(char[] pass){
        return pass.length >= GestlabConstants.PASSWD_MIN_SIZE;
    }
    
    /**
     * Mètode per codificar el password de l'usuari
     * @author manel bosch
     * @param pass password a codificar
     * @return String amb el password codificat
     */
    public String encodePasswd(char[] pass){
        byte[]  bytesEncoded = Base64.encodeBase64(String.valueOf(pass).getBytes());
        return new String(bytesEncoded);
    }
    
    /**
     * Mètode per netejar els camps d'entrada de dades
     * @author manel bosch
     */
    public void cleanFields(){
        jTextFieldLogin.setText("");
        jPasswordField.setText("");
    }
}
