
package gestlab.view;

//import gestlab.model.Producto;

/**
 * Classe per gestionar l'entrada/modificació de dades d'un producte
 * @author manel bosch
 */
public class ProductDialog extends javax.swing.JDialog {
    
    //Producto producto;

    /**
     * Crea una finestra per entrar un nou producte
     * @author manel bosch
     * @param parent finestra mare
     * @param modal manté el focus fins a tancar la finestra
     */
    public ProductDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    
    /**
     * Crea un nou formulari per modificar dades d'un producte passat per paràmetre
     * @param parent
     * @param modal
     * @param p Producte a modificar
     */
    /*
    public EquipDialog(java.awt.Frame parent, boolean modal, Producto p) {
        super(parent, modal);
        initComponents();
        //equipo = e;
        fillEquipData(e);
    }
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitol = new javax.swing.JLabel();
        jPanelDadesProducte = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabelCompany = new javax.swing.JLabel();
        jTextFieldCompany = new javax.swing.JTextField();
        jLabelReference = new javax.swing.JLabel();
        jTextFieldReference = new javax.swing.JTextField();
        jLabelUnits = new javax.swing.JLabel();
        jTextFieldUnits = new javax.swing.JTextField();
        jLabelQuantity = new javax.swing.JLabel();
        jLabelIdProducte = new javax.swing.JLabel();
        jTextFieldIdProducte = new javax.swing.JTextField();
        jTextFieldQuantity = new javax.swing.JTextField();
        jPanelBotons = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelTitol.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabelTitol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitol.setText("GestLab: Producte");

        jLabelName.setText("Nom:");

        jLabelCompany.setText("Casa comercial:");

        jLabelReference.setText("Referència:");

        jLabelUnits.setText("Unitats:");

        jLabelQuantity.setText("Quantitat:");

        jLabelIdProducte.setText("ID:");

        javax.swing.GroupLayout jPanelDadesProducteLayout = new javax.swing.GroupLayout(jPanelDadesProducte);
        jPanelDadesProducte.setLayout(jPanelDadesProducteLayout);
        jPanelDadesProducteLayout.setHorizontalGroup(
            jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadesProducteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadesProducteLayout.createSequentialGroup()
                        .addComponent(jLabelIdProducte)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDadesProducteLayout.createSequentialGroup()
                        .addGroup(jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addComponent(jLabelCompany)
                            .addComponent(jLabelReference)
                            .addComponent(jLabelUnits)
                            .addComponent(jLabelQuantity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldReference, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jTextFieldCompany)
                    .addComponent(jTextFieldNom)
                    .addComponent(jTextFieldIdProducte)
                    .addComponent(jTextFieldUnits, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jTextFieldQuantity))
                .addContainerGap())
        );
        jPanelDadesProducteLayout.setVerticalGroup(
            jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadesProducteLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdProducte)
                    .addComponent(jTextFieldIdProducte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCompany))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelReference))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUnits))
                .addGap(20, 20, 20)
                .addGroup(jPanelDadesProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantity)
                    .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jButtonSave.setText("Guardar");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonClear.setText("Netejar");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel·lar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonsLayout = new javax.swing.GroupLayout(jPanelBotons);
        jPanelBotons.setLayout(jPanelBotonsLayout);
        jPanelBotonsLayout.setHorizontalGroup(
            jPanelBotonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBotonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMessage)
                    .addGroup(jPanelBotonsLayout.createSequentialGroup()
                        .addComponent(jButtonSave)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonClear)
                        .addGap(31, 31, 31)
                        .addComponent(jButtonCancel)))
                .addGap(168, 168, 168))
        );

        jPanelBotonsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancel, jButtonClear, jButtonSave});

        jPanelBotonsLayout.setVerticalGroup(
            jPanelBotonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonsLayout.createSequentialGroup()
                .addComponent(jLabelMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanelBotonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonCancel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDadesProducte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelBotons, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitol)
                .addGap(18, 18, 18)
                .addComponent(jPanelDadesProducte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * Mètode per netejar les dades introduides
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextFieldIdProducte.setText("");
        jTextFieldNom.setText("");
        jTextFieldCompany.setText("");
        jTextFieldReference.setText("");
        jTextFieldUnits.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * Mètode per cancelar l'entrada de dades i per tant tancar la finestra
     * @author manel bosch
     * @param evt Event que representa prémer el botó
     */
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelCompany;
    private javax.swing.JLabel jLabelIdProducte;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelReference;
    private javax.swing.JLabel jLabelTitol;
    private javax.swing.JLabel jLabelUnits;
    private javax.swing.JPanel jPanelBotons;
    private javax.swing.JPanel jPanelDadesProducte;
    private javax.swing.JTextField jTextFieldCompany;
    private javax.swing.JTextField jTextFieldIdProducte;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldReference;
    private javax.swing.JTextField jTextFieldUnits;
    // End of variables declaration//GEN-END:variables

    /**
     * Mètode per omplir els camps amb les dades del producte passat com a paràmetre
     * @author manel bosch
     * @param p Producte
     */
    /*
    private void fillEquipData(Producto p){
        jTextFieldIdEquip.setText();
        jTextFieldNom.setText();
        jTextFieldMarca.setText();
        jTextFieldModel.setText();
        jTextFieldInventari.setText();
    }
    */
    
    /**
     * Mètode per llegir els camps amb les dades entrades per crear el producte
     * @author manel bosch
     * @return Producte amb les dades entrades
     */
    /*
    private Usuario getEquipData(){
        if(checkFilledFields()){
            Equipo e = new Equipo();
            
            return e;
        }else{
            jLabelMessage.setText("Siusplau, omple tots els camps obligatoris");
            return null;
        }
    }
    */
    
    /**
     * Mètode per saber si tots els camps necessaris estan plens
     * @return true o false
     */
    private boolean checkFilledFields(){
        return !(jTextFieldIdProducte.getText().equals("")
                ||jTextFieldNom.getText().equals("")
                ||jTextFieldCompany.getText().equals("")
                ||jTextFieldUnits.getText().equals(""));
        //Falta acabar
    }
}
